[package]
name = "smithay"
version = "0.3.0"
authors = ["Victor Berger <victor.berger@m4x.org>", "Drakulix (Victor Brekenfeld)"]
license = "MIT"
description = "Smithay is a library for writing wayland compositors."
repository = "https://github.com/Smithay/smithay"
edition = "2021"
readme = "README.md"
homepage = "https://smithay.github.io/"
keywords = ["wayland", "compositor", "graphics", "server"]
categories = ["gui"]

[package.metadata.docs.rs]
features = ["test_all_features"]
rustdoc-args = ["--cfg", "docsrs"]

[workspace]
members = [
    "smallvil",
    "anvil",
    "wlcs_anvil"
]

[dependencies]
cfg-if = "1.0.0"
appendlist = "1.4"
bitflags = "1"
calloop = { git = "https://github.com/EchidnaHQ/calloop.git", branch = "android-fix" }
cgmath = "0.18.0"
dbus = { version = "0.9.4", optional = true }
downcast-rs = "1.2.0"


indexmap = { version = "1.7", optional = true }
lazy_static = "1"
libc = "0.2.103"

libloading = { version="0.7.0", optional = true } 
nix = "0.22"
once_cell = "1.8.0"
rand = "0.8.4"
slog = "2"
slog-stdlog = { version = "4", optional = true }
tempfile = { version = "3.0", optional = true }
thiserror = "1.0.25"

wayland-egl = {  path = "../wayland-rs/wayland-egl", optional = true }
wayland-protocols = {  path = "../wayland-rs/wayland-protocols", features = ["unstable", "staging", "server"], optional = true }
wayland-protocols-wlr = {   path = "../wayland-rs/wayland-protocols-wlr", features = ["server"]}
wayland-server = {   path = "../wayland-rs/wayland-server",  optional = true }
wayland-sys = {  path = "../wayland-rs/wayland-sys",  optional = true }
wayland-backend = {  path = "../wayland-rs/wayland-backend", optional = true }
winit = { version = "0.26", optional = true }
x11rb = { version = "0.9.0", optional = true }
xkbcommon = "0.4.0"
scan_fmt = { version = "0.2.3", default-features = false }

# This dependency will only be included when targeting Android
[target.'cfg(target_os = "android")'.dependencies]
ndk-glue = "0.6.2" # Substitute this with the latest ndk-glue version you wish to use


[target.'cfg(not(target_os = "android"))'.dependencies]
udev = { version = "0.6", optional = true }
libseat= { version = "0.1.1", optional = true }
input = { version = "0.7", default-features = false, features=["libinput_1_19"], optional = true }
drm-fourcc = "^2.1.1"
drm = { version = "0.6.1", optional = true }
drm-ffi = { version = "0.2.1", optional = true }
gbm = { version = "0.8.0", optional = true, default-features = false }

[patch.crates-io]
winit = { git = "https://github.com/rust-windowing/winit", rev = "4c39b3188cee29548761b57f38e4aa046cbe31ea" }

[dev-dependencies]
slog-term = "2.3"

[build-dependencies]
gl_generator = { version = "0.14", optional = true }
pkg-config = { version = "0.3.17", optional = true }

[features]
default = [  "backend_winit", "desktop", "renderer_gl", "xwayland", "wayland_frontend", "slog-stdlog"]
backend_winit = ["winit", "backend_egl", "wayland-egl", "renderer_gl"]
backend_x11 = ["x11rb", "x11rb/dri3", "x11rb/xfixes", "x11rb/present", "x11rb_event_source", "backend_gbm", "backend_drm", "backend_egl"]
backend_drm = ["drm", "drm-ffi"]
backend_gbm = ["gbm"]
backend_egl = ["gl_generator", "libloading"]
backend_libinput = ["input"]
backend_session = []
backend_udev = ["udev", "input/udev"]
backend_session_logind = ["dbus", "backend_session", "pkg-config"]
backend_session_elogind = ["backend_session_logind"]
backend_session_libseat = ["backend_session", "libseat"]
desktop = ["indexmap", "wayland_frontend"]
renderer_gl = ["gl_generator", "backend_egl"]
renderer_multi = ["backend_drm"]
use_system_lib = ["wayland_frontend", "wayland-backend/server_system", "wayland-sys"]
wayland_frontend = ["wayland-server", "wayland-protocols", "tempfile"]
x11rb_event_source = ["x11rb"]
xwayland = ["wayland_frontend"]
test_all_features = ["default"]

[[example]]
name = "raw_drm"
required-features = ["backend_drm"]

[[example]]
name = "minimal"
required-features = ["backend_winit", "renderer_gl", "wayland_frontend"]

[[example]]
name = "seat"
required-features = ["wayland_frontend"]

[[example]]
name = "compositor"
required-features = ["wayland_frontend"]
